name: Deploy PROD Worker

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
# Reuse the deploy job from deploy.yml
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "prod"
    secrets: inherit